### ISSUE TITLE
Missing moving tiles on the way to rover

### ISSUE THREAD

**Issue by BloodSweatAndCode** [BloodSweatAndCode/cv2r#116]
https://clips.twitch.tv/BitterMoistAmazonUncleNox

Might need to get rid of projectile enemies

**Comment by burbruee** [comment]
seed: rq0oh8fB62II0R1e

**Comment by tonylukasavage** [comment]
another example in debious woods:

https://clips.twitch.tv/HumbleDeadPoultryWoofer

seed: UofA83NMSt53

**Comment by BloodSweatAndCode** [comment]
ok, both are the `0x03` sprite table, so that's an interesting commonality

**Comment by BloodSweatAndCode** [comment]
Another on, same enemy set

https://clips.twitch.tv/PerfectCallousAardvarkPMSTwin

seed: MinsConsultancyDrugUpdate
