### ISSUE TITLE
Adjust sales prices to progressively increase for progression items

### ISSUE THREAD

**Issue by tonylukasavage** [BloodSweatAndCode/cv2r#29]
Right now all items have hard-coded prices, and your white crystal might be priced like a red crystal depending on the item stored in the actor. I want to apply the same logic I do for sales icons for crystals to modify the sales prices as well as you progress.

**Comment by BloodSweatAndCode** [comment]
Prices will not be made progressive to avoid in-game confusion if merchant prices are changing dynamically. Instead this will be handled with some price regulation in #103
