### ISSUE TITLE
Fix the "low priority sprite" rendering

### ISSUE THREAD

**Issue by tonylukasavage** [BloodSweatAndCode/cv2r#30]
In marshes there's a hidden "low priority sprite" that indicates that all sprites should be rendered behind the marsh. On any non-marsh pattern table, this sprite shows up slightly glitched and doesn't render sprites behind marsh properly all the time.

**Comment by BloodSweatAndCode** [comment]
Any screen that has a marsh expects the last 2 bytes of the sprite table to be empty. This is true of every sprite table _except_ the Death mansion one.
