### ISSUE TITLE
No mansion blobs in screens with no ceiling

### ISSUE THREAD

**Issue by tonylukasavage** [BloodSweatAndCode/cv2r#32]
Mansion blobs have a tendency to jump up to a ceiling that isn't there and disappear on most overworld screen. There are a few exceptions like Dabi's Path. We'll need to update [lib/core.js](../tree/master/lib/core.js) to note all screens that have a ceiling in the overworld, and then spawn mansion blobs only in mansions or overworld screens that have ceilings.

**Comment by BloodSweatAndCode** [comment]
resolved in #97
