### ISSUE TITLE
A flag for "practice" mode

### ISSUE THREAD

**Issue by tonylukasavage** [BloodSweatAndCode/cv2r#34]
Much like canight's practice ROM, it would be nice to have a flag that allowed us to list on the screen key values that help players practice new strats for the rando. Off the top of my head, y subpixel value is the only value I can think of, but I'll rely on comments in this issue to augment that list.

**Comment by burbruee** [comment]
I think boss hp during boss fights would be good. If it's possible to "attach" this text value below or above the boss sprite so it moves along with the boss then even better.

**Comment by Canite** [comment]
> I think boss hp during boss fights would be good. If it's possible to "attach" this text value below or above the boss sprite so it moves along with the boss then even better.

If you know where the x/y coordinates of the boss is stored, this shouldn't be too hard to do but are all of the bosses the same size? I think the x/y of the bosses are stored as their top-left position

**Comment by tonylukasavage** [comment]
TBH, I think all of this could more appropriately be handled in the practice ROM that already exists, rather than making a rando specific one. I'm gonna close this one unless someone has a real compelling reason to make a rando-specific practice ROM
