### ISSUE TITLE
"Elite" flags

### ISSUE THREAD

**Issue by tonylukasavage** [BloodSweatAndCode/cv2r#35]
This is a collection of potential "elite" flags for top players, or races amongst top players:

* jovah warp penality
* text encrypted until some item is attained (eyeball???)
* Changing invisible/holy water blocks
* Change criteria to break bridge wall to drac's mansion, put hints to criteria in books/npcs
* randomize items into books
* Disable quick kill bug

More suggestions can be made in the comments of this issue

**Comment by burbruee** [comment]
If quick kill will be taken out, then I also suggest to:

- Force whip downgrade when entering Dracula's castle. (Thorn Whip?)

to make the final fight an actual challenge.

**Comment by burbruee** [comment]
Graveyard jump in logic. (Blue crystal or jova warp required to RETURN BACK after the water passageway)
