### ISSUE TITLE
Additional fast travel locations

### ISSUE THREAD

**Issue by tonylukasavage** [BloodSweatAndCode/cv2r#39]
Design and implement a way to include more fast travel in the game. Some ideas are:

* Tying the ability for fast travel to some of the more useless items (diamond, cross, silver knife, etc...)
* Fast travel between churches

**Comment by BloodSweatAndCode** [comment]
closing this for now as there's a bit of a consensus that jovah warp is enough fast travel. Will re-open if a compelling case is made.
